### 1001买入
POST http://localhost:8080/api/v1/orders/place
Content-Type: application/json

{
    "orderId": "10005",
    "userId": 1001,
    "action": "BID",
    "reservePrice":50.0,
    "orderType": "GTC",
    "price": 50.0,
    "size": 1,
    "symbol": 10086
}

### 1002卖出
POST http://localhost:8080/api/v1/orders/place
Content-Type: application/json

{
    "orderId": "10006",
    "userId": 1002,
    "action": "ASK",
    "reservePrice":50.0,
    "orderType": "GTC",
    "price": 50.0,
    "size": 1,
    "symbol": 10086
}